/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { readRecords } from "../../funcs/readRecords.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.TriggerReadRequest$inboundSchema,
};

export const tool$readRecords: ToolDefinition<typeof args> = {
  name: "read_records",
  description: `Trigger a read

Triggers reading data from a SaaS instance. See [Trigger a read](https://docs.withampersand.com/define-integrations/read-actions#trigger-a-read) for details.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await readRecords(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
