/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  billingAccountCreateBillingAccountSession,
  CreateBillingAccountSessionAcceptEnum,
} from "../funcs/billingAccountCreateBillingAccountSession.js";
import {
  billingAccountGetOrgBillingAccount,
  GetOrgBillingAccountAcceptEnum,
} from "../funcs/billingAccountGetOrgBillingAccount.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export { GetOrgBillingAccountAcceptEnum } from "../funcs/billingAccountGetOrgBillingAccount.js";

export { CreateBillingAccountSessionAcceptEnum } from "../funcs/billingAccountCreateBillingAccountSession.js";

export class BillingAccount extends ClientSDK {
  /**
   * Get the billing account for an organization
   */
  async getOrgBillingAccount(
    request: operations.GetOrgBillingAccountRequest,
    options?: RequestOptions & {
      acceptHeaderOverride?: GetOrgBillingAccountAcceptEnum;
    },
  ): Promise<operations.GetOrgBillingAccountResponse> {
    return unwrapAsync(billingAccountGetOrgBillingAccount(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a portal session for a billing account
   */
  async createBillingAccountSession(
    request: operations.CreateBillingAccountSessionRequest,
    options?: RequestOptions & {
      acceptHeaderOverride?: CreateBillingAccountSessionAcceptEnum;
    },
  ): Promise<operations.CreateBillingAccountSessionResponse> {
    return unwrapAsync(billingAccountCreateBillingAccountSession(
      this,
      request,
      options,
    ));
  }
}
