/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const GetObjectMetadataServerList = [
  "https://api.withampersand.com/v1",
] as const;

export type GetObjectMetadataRequest = {
  /**
   * Project ID or name
   */
  projectIdOrName: string;
  /**
   * Integration ID
   */
  integrationId: string;
  /**
   * Object name (mapped or unmapped)
   */
  objectName: string;
  /**
   * The groupRef for the installation
   */
  groupRef?: string | undefined;
};

/**
 * A Problem Details object (RFC 9457).
 *
 * @remarks
 *
 * Additional properties specific to the problem type may be present.
 */
export type GetObjectMetadataObjectsAndFieldsResponseBody = {
  /**
   * An absolute URI that identifies the problem type
   */
  type?: string | undefined;
  /**
   * An absolute URI that, when dereferenced, provides human-readable documentation for the problem type (e.g. using HTML).
   */
  href?: string | undefined;
  /**
   * A short summary of the problem type. Written in English and readable for engineers (usually not suited for non technical stakeholders and not localized).
   */
  title?: string | undefined;
  /**
   * The HTTP status code generated by the origin server for this occurrence of the problem.
   */
  status?: number | undefined;
  /**
   * A human-readable explanation specific to this occurrence of the problem
   */
  detail?: string | undefined;
  /**
   * An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
   */
  instance?: string | undefined;
  /**
   * The subsystem that generated the problem
   */
  subsystem?: string | undefined;
  /**
   * The time the problem occurred, formatted as RFC-3339
   */
  time?: Date | undefined;
  /**
   * A unique identifier for the request, useful for debugging
   */
  requestId?: string | undefined;
  /**
   * A list of problems that caused this problem. This can be used to represent multiple
   *
   * @remarks
   * root causes. There is no guaranteed ordering of the causes.
   */
  causes?: Array<string> | undefined;
  /**
   * A brief description of how to resolve the problem
   */
  remedy?: string | undefined;
  /**
   * An email address to contact for support
   */
  supportEmail?: string | undefined;
  /**
   * A phone number to contact for support
   */
  supportPhone?: string | undefined;
  /**
   * A URL to contact for support
   */
  supportUrl?: string | undefined;
  /**
   * Whether the request can be retried
   */
  retryable?: boolean | undefined;
  /**
   * A timestamp after which the request can be retried, formatted as RFC-3339
   */
  retryAfter?: Date | undefined;
  /**
   * Additional context for the problem
   */
  context?: { [k: string]: any } | undefined;
};

/**
 * A normalized field type
 */
export const ValueType = {
  String: "string",
  Boolean: "boolean",
  SingleSelect: "singleSelect",
  MultiSelect: "multiSelect",
  Date: "date",
  Datetime: "datetime",
  Int: "int",
  Float: "float",
  Other: "other",
} as const;
/**
 * A normalized field type
 */
export type ValueType = ClosedEnum<typeof ValueType>;

/**
 * Represents a field value
 */
export type Values = {
  /**
   * The internal value used by the system
   */
  value: string;
  /**
   * The human-readable display value
   */
  displayValue: string;
};

export type Fields = {
  /**
   * The name of the field from the provider API.
   */
  fieldName: string;
  /**
   * The display name of the field from the provider API.
   */
  displayName: string;
  /**
   * A normalized field type
   */
  valueType?: ValueType | undefined;
  /**
   * Raw field type from the provider API.
   */
  providerType?: string | undefined;
  /**
   * Whether the field is read-only.
   */
  readOnly?: boolean | undefined;
  /**
   * If the valueType is singleSelect or multiSelect, this is a list of possible values
   */
  values?: Array<Values> | undefined;
};

/**
 * The retrieved object metadata
 */
export type GetObjectMetadataResponseBody = {
  /**
   * The provider name of the object
   */
  name: string;
  /**
   * Human-readable name of the object
   */
  displayName?: string | undefined;
  mappedObjectName?: string | undefined;
  /**
   * Map of field metadata keyed by field name
   */
  fields: { [k: string]: Fields };
};

export type GetObjectMetadataResponse =
  | GetObjectMetadataResponseBody
  | GetObjectMetadataObjectsAndFieldsResponseBody;

/** @internal */
export const GetObjectMetadataRequest$inboundSchema: z.ZodType<
  GetObjectMetadataRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectIdOrName: z.string(),
  integrationId: z.string(),
  objectName: z.string(),
  groupRef: z.string().optional(),
});

/** @internal */
export type GetObjectMetadataRequest$Outbound = {
  projectIdOrName: string;
  integrationId: string;
  objectName: string;
  groupRef?: string | undefined;
};

/** @internal */
export const GetObjectMetadataRequest$outboundSchema: z.ZodType<
  GetObjectMetadataRequest$Outbound,
  z.ZodTypeDef,
  GetObjectMetadataRequest
> = z.object({
  projectIdOrName: z.string(),
  integrationId: z.string(),
  objectName: z.string(),
  groupRef: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetObjectMetadataRequest$ {
  /** @deprecated use `GetObjectMetadataRequest$inboundSchema` instead. */
  export const inboundSchema = GetObjectMetadataRequest$inboundSchema;
  /** @deprecated use `GetObjectMetadataRequest$outboundSchema` instead. */
  export const outboundSchema = GetObjectMetadataRequest$outboundSchema;
  /** @deprecated use `GetObjectMetadataRequest$Outbound` instead. */
  export type Outbound = GetObjectMetadataRequest$Outbound;
}

export function getObjectMetadataRequestToJSON(
  getObjectMetadataRequest: GetObjectMetadataRequest,
): string {
  return JSON.stringify(
    GetObjectMetadataRequest$outboundSchema.parse(getObjectMetadataRequest),
  );
}

export function getObjectMetadataRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetObjectMetadataRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetObjectMetadataRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetObjectMetadataRequest' from JSON`,
  );
}

/** @internal */
export const GetObjectMetadataObjectsAndFieldsResponseBody$inboundSchema:
  z.ZodType<
    GetObjectMetadataObjectsAndFieldsResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    type: z.string().default("about:blank"),
    href: z.string().optional(),
    title: z.string().optional(),
    status: z.number().int().optional(),
    detail: z.string().optional(),
    instance: z.string().optional(),
    subsystem: z.string().optional(),
    time: z.string().datetime({ offset: true }).transform(v => new Date(v))
      .optional(),
    requestId: z.string().optional(),
    causes: z.array(z.string()).optional(),
    remedy: z.string().optional(),
    supportEmail: z.string().optional(),
    supportPhone: z.string().optional(),
    supportUrl: z.string().optional(),
    retryable: z.boolean().optional(),
    retryAfter: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ).optional(),
    context: z.record(z.any()).optional(),
  });

/** @internal */
export type GetObjectMetadataObjectsAndFieldsResponseBody$Outbound = {
  type: string;
  href?: string | undefined;
  title?: string | undefined;
  status?: number | undefined;
  detail?: string | undefined;
  instance?: string | undefined;
  subsystem?: string | undefined;
  time?: string | undefined;
  requestId?: string | undefined;
  causes?: Array<string> | undefined;
  remedy?: string | undefined;
  supportEmail?: string | undefined;
  supportPhone?: string | undefined;
  supportUrl?: string | undefined;
  retryable?: boolean | undefined;
  retryAfter?: string | undefined;
  context?: { [k: string]: any } | undefined;
};

/** @internal */
export const GetObjectMetadataObjectsAndFieldsResponseBody$outboundSchema:
  z.ZodType<
    GetObjectMetadataObjectsAndFieldsResponseBody$Outbound,
    z.ZodTypeDef,
    GetObjectMetadataObjectsAndFieldsResponseBody
  > = z.object({
    type: z.string().default("about:blank"),
    href: z.string().optional(),
    title: z.string().optional(),
    status: z.number().int().optional(),
    detail: z.string().optional(),
    instance: z.string().optional(),
    subsystem: z.string().optional(),
    time: z.date().transform(v => v.toISOString()).optional(),
    requestId: z.string().optional(),
    causes: z.array(z.string()).optional(),
    remedy: z.string().optional(),
    supportEmail: z.string().optional(),
    supportPhone: z.string().optional(),
    supportUrl: z.string().optional(),
    retryable: z.boolean().optional(),
    retryAfter: z.date().transform(v => v.toISOString()).optional(),
    context: z.record(z.any()).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetObjectMetadataObjectsAndFieldsResponseBody$ {
  /** @deprecated use `GetObjectMetadataObjectsAndFieldsResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    GetObjectMetadataObjectsAndFieldsResponseBody$inboundSchema;
  /** @deprecated use `GetObjectMetadataObjectsAndFieldsResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    GetObjectMetadataObjectsAndFieldsResponseBody$outboundSchema;
  /** @deprecated use `GetObjectMetadataObjectsAndFieldsResponseBody$Outbound` instead. */
  export type Outbound = GetObjectMetadataObjectsAndFieldsResponseBody$Outbound;
}

export function getObjectMetadataObjectsAndFieldsResponseBodyToJSON(
  getObjectMetadataObjectsAndFieldsResponseBody:
    GetObjectMetadataObjectsAndFieldsResponseBody,
): string {
  return JSON.stringify(
    GetObjectMetadataObjectsAndFieldsResponseBody$outboundSchema.parse(
      getObjectMetadataObjectsAndFieldsResponseBody,
    ),
  );
}

export function getObjectMetadataObjectsAndFieldsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  GetObjectMetadataObjectsAndFieldsResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetObjectMetadataObjectsAndFieldsResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetObjectMetadataObjectsAndFieldsResponseBody' from JSON`,
  );
}

/** @internal */
export const ValueType$inboundSchema: z.ZodNativeEnum<typeof ValueType> = z
  .nativeEnum(ValueType);

/** @internal */
export const ValueType$outboundSchema: z.ZodNativeEnum<typeof ValueType> =
  ValueType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ValueType$ {
  /** @deprecated use `ValueType$inboundSchema` instead. */
  export const inboundSchema = ValueType$inboundSchema;
  /** @deprecated use `ValueType$outboundSchema` instead. */
  export const outboundSchema = ValueType$outboundSchema;
}

/** @internal */
export const Values$inboundSchema: z.ZodType<Values, z.ZodTypeDef, unknown> = z
  .object({
    value: z.string(),
    displayValue: z.string(),
  });

/** @internal */
export type Values$Outbound = {
  value: string;
  displayValue: string;
};

/** @internal */
export const Values$outboundSchema: z.ZodType<
  Values$Outbound,
  z.ZodTypeDef,
  Values
> = z.object({
  value: z.string(),
  displayValue: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Values$ {
  /** @deprecated use `Values$inboundSchema` instead. */
  export const inboundSchema = Values$inboundSchema;
  /** @deprecated use `Values$outboundSchema` instead. */
  export const outboundSchema = Values$outboundSchema;
  /** @deprecated use `Values$Outbound` instead. */
  export type Outbound = Values$Outbound;
}

export function valuesToJSON(values: Values): string {
  return JSON.stringify(Values$outboundSchema.parse(values));
}

export function valuesFromJSON(
  jsonString: string,
): SafeParseResult<Values, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Values$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Values' from JSON`,
  );
}

/** @internal */
export const Fields$inboundSchema: z.ZodType<Fields, z.ZodTypeDef, unknown> = z
  .object({
    fieldName: z.string(),
    displayName: z.string(),
    valueType: ValueType$inboundSchema.optional(),
    providerType: z.string().optional(),
    readOnly: z.boolean().optional(),
    values: z.array(z.lazy(() => Values$inboundSchema)).optional(),
  });

/** @internal */
export type Fields$Outbound = {
  fieldName: string;
  displayName: string;
  valueType?: string | undefined;
  providerType?: string | undefined;
  readOnly?: boolean | undefined;
  values?: Array<Values$Outbound> | undefined;
};

/** @internal */
export const Fields$outboundSchema: z.ZodType<
  Fields$Outbound,
  z.ZodTypeDef,
  Fields
> = z.object({
  fieldName: z.string(),
  displayName: z.string(),
  valueType: ValueType$outboundSchema.optional(),
  providerType: z.string().optional(),
  readOnly: z.boolean().optional(),
  values: z.array(z.lazy(() => Values$outboundSchema)).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Fields$ {
  /** @deprecated use `Fields$inboundSchema` instead. */
  export const inboundSchema = Fields$inboundSchema;
  /** @deprecated use `Fields$outboundSchema` instead. */
  export const outboundSchema = Fields$outboundSchema;
  /** @deprecated use `Fields$Outbound` instead. */
  export type Outbound = Fields$Outbound;
}

export function fieldsToJSON(fields: Fields): string {
  return JSON.stringify(Fields$outboundSchema.parse(fields));
}

export function fieldsFromJSON(
  jsonString: string,
): SafeParseResult<Fields, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Fields$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Fields' from JSON`,
  );
}

/** @internal */
export const GetObjectMetadataResponseBody$inboundSchema: z.ZodType<
  GetObjectMetadataResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  displayName: z.string().optional(),
  mappedObjectName: z.string().optional(),
  fields: z.record(z.lazy(() => Fields$inboundSchema)),
});

/** @internal */
export type GetObjectMetadataResponseBody$Outbound = {
  name: string;
  displayName?: string | undefined;
  mappedObjectName?: string | undefined;
  fields: { [k: string]: Fields$Outbound };
};

/** @internal */
export const GetObjectMetadataResponseBody$outboundSchema: z.ZodType<
  GetObjectMetadataResponseBody$Outbound,
  z.ZodTypeDef,
  GetObjectMetadataResponseBody
> = z.object({
  name: z.string(),
  displayName: z.string().optional(),
  mappedObjectName: z.string().optional(),
  fields: z.record(z.lazy(() => Fields$outboundSchema)),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetObjectMetadataResponseBody$ {
  /** @deprecated use `GetObjectMetadataResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetObjectMetadataResponseBody$inboundSchema;
  /** @deprecated use `GetObjectMetadataResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetObjectMetadataResponseBody$outboundSchema;
  /** @deprecated use `GetObjectMetadataResponseBody$Outbound` instead. */
  export type Outbound = GetObjectMetadataResponseBody$Outbound;
}

export function getObjectMetadataResponseBodyToJSON(
  getObjectMetadataResponseBody: GetObjectMetadataResponseBody,
): string {
  return JSON.stringify(
    GetObjectMetadataResponseBody$outboundSchema.parse(
      getObjectMetadataResponseBody,
    ),
  );
}

export function getObjectMetadataResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetObjectMetadataResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetObjectMetadataResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetObjectMetadataResponseBody' from JSON`,
  );
}

/** @internal */
export const GetObjectMetadataResponse$inboundSchema: z.ZodType<
  GetObjectMetadataResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => GetObjectMetadataResponseBody$inboundSchema),
  z.lazy(() => GetObjectMetadataObjectsAndFieldsResponseBody$inboundSchema),
]);

/** @internal */
export type GetObjectMetadataResponse$Outbound =
  | GetObjectMetadataResponseBody$Outbound
  | GetObjectMetadataObjectsAndFieldsResponseBody$Outbound;

/** @internal */
export const GetObjectMetadataResponse$outboundSchema: z.ZodType<
  GetObjectMetadataResponse$Outbound,
  z.ZodTypeDef,
  GetObjectMetadataResponse
> = z.union([
  z.lazy(() => GetObjectMetadataResponseBody$outboundSchema),
  z.lazy(() => GetObjectMetadataObjectsAndFieldsResponseBody$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetObjectMetadataResponse$ {
  /** @deprecated use `GetObjectMetadataResponse$inboundSchema` instead. */
  export const inboundSchema = GetObjectMetadataResponse$inboundSchema;
  /** @deprecated use `GetObjectMetadataResponse$outboundSchema` instead. */
  export const outboundSchema = GetObjectMetadataResponse$outboundSchema;
  /** @deprecated use `GetObjectMetadataResponse$Outbound` instead. */
  export type Outbound = GetObjectMetadataResponse$Outbound;
}

export function getObjectMetadataResponseToJSON(
  getObjectMetadataResponse: GetObjectMetadataResponse,
): string {
  return JSON.stringify(
    GetObjectMetadataResponse$outboundSchema.parse(getObjectMetadataResponse),
  );
}

export function getObjectMetadataResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetObjectMetadataResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetObjectMetadataResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetObjectMetadataResponse' from JSON`,
  );
}
