/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const ListApiKeysServerList = [
  "https://api.withampersand.com/v1",
] as const;

export type ListApiKeysRequest = {
  projectIdOrName: string;
  /**
   * Whether to include only active API keys. If false, all API keys are included.
   */
  active?: boolean | undefined;
};

/**
 * A Problem Details object (RFC 9457).
 *
 * @remarks
 *
 * Additional properties specific to the problem type may be present.
 */
export type ListApiKeysResponseBody = {
  /**
   * An absolute URI that identifies the problem type
   */
  type?: string | undefined;
  /**
   * An absolute URI that, when dereferenced, provides human-readable documentation for the problem type (e.g. using HTML).
   */
  href?: string | undefined;
  /**
   * A short summary of the problem type. Written in English and readable for engineers (usually not suited for non technical stakeholders and not localized).
   */
  title?: string | undefined;
  /**
   * The HTTP status code generated by the origin server for this occurrence of the problem.
   */
  status?: number | undefined;
  /**
   * A human-readable explanation specific to this occurrence of the problem
   */
  detail?: string | undefined;
  /**
   * An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
   */
  instance?: string | undefined;
  /**
   * The subsystem that generated the problem
   */
  subsystem?: string | undefined;
  /**
   * The time the problem occurred, formatted as RFC-3339
   */
  time?: Date | undefined;
  /**
   * A unique identifier for the request, useful for debugging
   */
  requestId?: string | undefined;
  /**
   * A list of problems that caused this problem. This can be used to represent multiple
   *
   * @remarks
   * root causes. There is no guaranteed ordering of the causes.
   */
  causes?: Array<string> | undefined;
  /**
   * A brief description of how to resolve the problem
   */
  remedy?: string | undefined;
  /**
   * An email address to contact for support
   */
  supportEmail?: string | undefined;
  /**
   * A phone number to contact for support
   */
  supportPhone?: string | undefined;
  /**
   * A URL to contact for support
   */
  supportUrl?: string | undefined;
  /**
   * Whether the request can be retried
   */
  retryable?: boolean | undefined;
  /**
   * A timestamp after which the request can be retried, formatted as RFC-3339
   */
  retryAfter?: Date | undefined;
  /**
   * Additional context for the problem
   */
  context?: { [k: string]: any } | undefined;
};

export type ListAPIKeysAPIKeyResponseBody = {
  /**
   * The API key.
   */
  key: string;
  /**
   * A short name for the API key.
   */
  label: string;
  /**
   * The scopes for the API key.
   */
  scopes: Array<string>;
  /**
   * The project ID.
   */
  projectId: string;
  /**
   * Whether the API key is active.
   */
  active?: boolean | undefined;
};

export type ListApiKeysResponse =
  | ListApiKeysResponseBody
  | Array<ListAPIKeysAPIKeyResponseBody>;

/** @internal */
export const ListApiKeysRequest$inboundSchema: z.ZodType<
  ListApiKeysRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectIdOrName: z.string(),
  active: z.boolean().optional(),
});

/** @internal */
export type ListApiKeysRequest$Outbound = {
  projectIdOrName: string;
  active?: boolean | undefined;
};

/** @internal */
export const ListApiKeysRequest$outboundSchema: z.ZodType<
  ListApiKeysRequest$Outbound,
  z.ZodTypeDef,
  ListApiKeysRequest
> = z.object({
  projectIdOrName: z.string(),
  active: z.boolean().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListApiKeysRequest$ {
  /** @deprecated use `ListApiKeysRequest$inboundSchema` instead. */
  export const inboundSchema = ListApiKeysRequest$inboundSchema;
  /** @deprecated use `ListApiKeysRequest$outboundSchema` instead. */
  export const outboundSchema = ListApiKeysRequest$outboundSchema;
  /** @deprecated use `ListApiKeysRequest$Outbound` instead. */
  export type Outbound = ListApiKeysRequest$Outbound;
}

export function listApiKeysRequestToJSON(
  listApiKeysRequest: ListApiKeysRequest,
): string {
  return JSON.stringify(
    ListApiKeysRequest$outboundSchema.parse(listApiKeysRequest),
  );
}

export function listApiKeysRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListApiKeysRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListApiKeysRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListApiKeysRequest' from JSON`,
  );
}

/** @internal */
export const ListApiKeysResponseBody$inboundSchema: z.ZodType<
  ListApiKeysResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.string().default("about:blank"),
  href: z.string().optional(),
  title: z.string().optional(),
  status: z.number().int().optional(),
  detail: z.string().optional(),
  instance: z.string().optional(),
  subsystem: z.string().optional(),
  time: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  requestId: z.string().optional(),
  causes: z.array(z.string()).optional(),
  remedy: z.string().optional(),
  supportEmail: z.string().optional(),
  supportPhone: z.string().optional(),
  supportUrl: z.string().optional(),
  retryable: z.boolean().optional(),
  retryAfter: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  context: z.record(z.any()).optional(),
});

/** @internal */
export type ListApiKeysResponseBody$Outbound = {
  type: string;
  href?: string | undefined;
  title?: string | undefined;
  status?: number | undefined;
  detail?: string | undefined;
  instance?: string | undefined;
  subsystem?: string | undefined;
  time?: string | undefined;
  requestId?: string | undefined;
  causes?: Array<string> | undefined;
  remedy?: string | undefined;
  supportEmail?: string | undefined;
  supportPhone?: string | undefined;
  supportUrl?: string | undefined;
  retryable?: boolean | undefined;
  retryAfter?: string | undefined;
  context?: { [k: string]: any } | undefined;
};

/** @internal */
export const ListApiKeysResponseBody$outboundSchema: z.ZodType<
  ListApiKeysResponseBody$Outbound,
  z.ZodTypeDef,
  ListApiKeysResponseBody
> = z.object({
  type: z.string().default("about:blank"),
  href: z.string().optional(),
  title: z.string().optional(),
  status: z.number().int().optional(),
  detail: z.string().optional(),
  instance: z.string().optional(),
  subsystem: z.string().optional(),
  time: z.date().transform(v => v.toISOString()).optional(),
  requestId: z.string().optional(),
  causes: z.array(z.string()).optional(),
  remedy: z.string().optional(),
  supportEmail: z.string().optional(),
  supportPhone: z.string().optional(),
  supportUrl: z.string().optional(),
  retryable: z.boolean().optional(),
  retryAfter: z.date().transform(v => v.toISOString()).optional(),
  context: z.record(z.any()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListApiKeysResponseBody$ {
  /** @deprecated use `ListApiKeysResponseBody$inboundSchema` instead. */
  export const inboundSchema = ListApiKeysResponseBody$inboundSchema;
  /** @deprecated use `ListApiKeysResponseBody$outboundSchema` instead. */
  export const outboundSchema = ListApiKeysResponseBody$outboundSchema;
  /** @deprecated use `ListApiKeysResponseBody$Outbound` instead. */
  export type Outbound = ListApiKeysResponseBody$Outbound;
}

export function listApiKeysResponseBodyToJSON(
  listApiKeysResponseBody: ListApiKeysResponseBody,
): string {
  return JSON.stringify(
    ListApiKeysResponseBody$outboundSchema.parse(listApiKeysResponseBody),
  );
}

export function listApiKeysResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListApiKeysResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListApiKeysResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListApiKeysResponseBody' from JSON`,
  );
}

/** @internal */
export const ListAPIKeysAPIKeyResponseBody$inboundSchema: z.ZodType<
  ListAPIKeysAPIKeyResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  key: z.string(),
  label: z.string(),
  scopes: z.array(z.string()),
  projectId: z.string(),
  active: z.boolean().optional(),
});

/** @internal */
export type ListAPIKeysAPIKeyResponseBody$Outbound = {
  key: string;
  label: string;
  scopes: Array<string>;
  projectId: string;
  active?: boolean | undefined;
};

/** @internal */
export const ListAPIKeysAPIKeyResponseBody$outboundSchema: z.ZodType<
  ListAPIKeysAPIKeyResponseBody$Outbound,
  z.ZodTypeDef,
  ListAPIKeysAPIKeyResponseBody
> = z.object({
  key: z.string(),
  label: z.string(),
  scopes: z.array(z.string()),
  projectId: z.string(),
  active: z.boolean().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListAPIKeysAPIKeyResponseBody$ {
  /** @deprecated use `ListAPIKeysAPIKeyResponseBody$inboundSchema` instead. */
  export const inboundSchema = ListAPIKeysAPIKeyResponseBody$inboundSchema;
  /** @deprecated use `ListAPIKeysAPIKeyResponseBody$outboundSchema` instead. */
  export const outboundSchema = ListAPIKeysAPIKeyResponseBody$outboundSchema;
  /** @deprecated use `ListAPIKeysAPIKeyResponseBody$Outbound` instead. */
  export type Outbound = ListAPIKeysAPIKeyResponseBody$Outbound;
}

export function listAPIKeysAPIKeyResponseBodyToJSON(
  listAPIKeysAPIKeyResponseBody: ListAPIKeysAPIKeyResponseBody,
): string {
  return JSON.stringify(
    ListAPIKeysAPIKeyResponseBody$outboundSchema.parse(
      listAPIKeysAPIKeyResponseBody,
    ),
  );
}

export function listAPIKeysAPIKeyResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ListAPIKeysAPIKeyResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListAPIKeysAPIKeyResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListAPIKeysAPIKeyResponseBody' from JSON`,
  );
}

/** @internal */
export const ListApiKeysResponse$inboundSchema: z.ZodType<
  ListApiKeysResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => ListApiKeysResponseBody$inboundSchema),
  z.array(z.lazy(() => ListAPIKeysAPIKeyResponseBody$inboundSchema)),
]);

/** @internal */
export type ListApiKeysResponse$Outbound =
  | ListApiKeysResponseBody$Outbound
  | Array<ListAPIKeysAPIKeyResponseBody$Outbound>;

/** @internal */
export const ListApiKeysResponse$outboundSchema: z.ZodType<
  ListApiKeysResponse$Outbound,
  z.ZodTypeDef,
  ListApiKeysResponse
> = z.union([
  z.lazy(() => ListApiKeysResponseBody$outboundSchema),
  z.array(z.lazy(() => ListAPIKeysAPIKeyResponseBody$outboundSchema)),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListApiKeysResponse$ {
  /** @deprecated use `ListApiKeysResponse$inboundSchema` instead. */
  export const inboundSchema = ListApiKeysResponse$inboundSchema;
  /** @deprecated use `ListApiKeysResponse$outboundSchema` instead. */
  export const outboundSchema = ListApiKeysResponse$outboundSchema;
  /** @deprecated use `ListApiKeysResponse$Outbound` instead. */
  export type Outbound = ListApiKeysResponse$Outbound;
}

export function listApiKeysResponseToJSON(
  listApiKeysResponse: ListApiKeysResponse,
): string {
  return JSON.stringify(
    ListApiKeysResponse$outboundSchema.parse(listApiKeysResponse),
  );
}

export function listApiKeysResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListApiKeysResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListApiKeysResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListApiKeysResponse' from JSON`,
  );
}
